[package]
name = "balance_proof"
type = "bin"
authors = ["Soul Team"]
compiler_version = ">=0.30.0"
description = "Balance proof circuit for deposits and withdrawals in Soul Exchange"

[dependencies]
