[package]
name = "cross_chain_proof"
type = "bin"
authors = ["ZASEON"]
description = "Optimized circuit for cross-chain proof relay"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
