[package]
name = "state_commitment"
type = "bin"
authors = ["Soul Protocol"]
compiler_version = ">=1.0.0"
description = "Optimized circuit for proving knowledge of state preimage using Poseidon hash"

[dependencies]
