[package]
name = "state_commitment"
type = "bin"
authors = ["ZASEON"]
description = "Optimized circuit for proving knowledge of state preimage using Poseidon hash"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
