[package]
name = "container"
type = "bin"
authors = ["ZASEON"]
description = "PCÂ³ Container Validity Circuit - proves container is valid without revealing contents"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
